language: python
os: linux
python:
   - "3.6"      # current default Python on Travis CI
# command to install dependencies
install:
 - pip install -r requirements.txt
# command to run tests

#virtualenv:
#  system_site_packages: true

script: pytest
